### PR TITLE
run interface wast generation in travis

### PR DESCRIPTION
**Pull request by jwasinger**
It appears this wasn't done previously, resulting in changes to the interface not being tested by travis.

### CODE REVIEW

**Comment by jwasinger** [comment]
ping @axic @cdetrio @lrettig @hugo-dc 

This should be merged before any other pending PRs.

**Comment by axic** [comment]
I'm not sure I understand it. It should be generated & committed in the PR by the person submitting it. 

Are you trying to ensure that they did that?

If so, in solc-bin, what I did was to run the generation and run `git diff` to see if any files have changed. If they did, the original PR didn't contain the proper changes, hence it is a failure. See: https://github.com/ethereum/solc-bin/blob/gh-pages/package.json#L17

**Comment by jwasinger** [comment]
> Are you trying to ensure that they did that?
Yes.
> If so, in solc-bin, what I did was to run the generation and run git diff to see if any files have changed. If they did, the original PR didn't contain the proper changes, hence it is a failure. See: https://github.com/ethereum/solc-bin/blob/gh-pages/package.json#L17

Okay I like this solution.

**Comment by axic** [comment]
@jwasinger can you push a broken change to test it works?

**Comment by axic** [comment]
@jwasinger seems to work well, if you want to remove that commit :)

**Pull request merged**
