### PR TITLE
Make CLI expect the EVM bytecode source file to be ASCII encoded as UTF8

### PR DESCRIPTION
**Pull request by jwasinger**
This makes interaction with Hera easier.

### CODE REVIEW

**Comment by axic** [comment]
Can you explain this PR a bit? Not entirely sure what it is doing.

**Comment by jwasinger** [comment]
The function `evm2wasm` expects the EVM bytecode as a buffer object.  This PR specifies that when invoked with the `-e` argument, `bin/evm2wasm.js` will load the specified file as hex formatted in plaintext ASCII and convert it to a buffer of EVM bytecode.

**Comment by axic** [comment]
But the line below that is doing that exact translation:
```
   // always consider input EVM as a hex string and translate that into binary for the next stage
   bytecode = Buffer.from(bytecode, 'hex')
```

**Comment by jwasinger** [comment]
ah.. whoops :feelsdumb:

**Pull request closed without merging**
