### PR TITLE
Fix CALLDATALOAD

### PR DESCRIPTION
**Pull request by kyteague**
This fix removes references to the deprecated `callDataCopy256` EEI API and replaces them with `callDataCopy`, which allows `evm2wasm` to be used with the latest version of Hera.

I tried using the fix from https://github.com/ewasm/evm2wasm/pull/193 but 1) the fix didn't seem to work and 2) the fix is tied to a refactor that doesn't look like will be merged anytime soon.

### CODE REVIEW

**Comment by jwasinger** [comment]
Thanks for the PR @kyteague.  A good way to get the PR included is to make sure that it [passes additional state tests](https://github.com/ewasm/evm2wasm/blob/master/circle.yml#L71-L75).

A relevant test case here is https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stMemoryTest/memReturn.json

**Comment by jwasinger** [comment]
This is the way to invoke `testeth`:  
```
 testeth -t GeneralStateTests/stMemoryTest -- --testpath ~/tests --singlenet "Byzantium" --singletest "memReturn" --vm ~/libhera.so --evmc evm2wasm.js=true
```

**Comment by kyteague** [comment]
Thanks for the info @jwasinger. I ran the `GeneralStateTests` locally, which seemed to only invoke `evm2wasm` during the `stMemoryTest` like you mentioned.

Here is the output. Let me know if I need to something else. I also saw that CircleCI passed as well.

```shell
$ testeth -t GeneralStateTests -- --testpath $TEST_PATH --singlenet "Byzantium" --singletest "memReturn" --vm $HERA_PATH --evmc evm2wasm.js=true
Running tests using path: "../../tests"
Running 47 test cases...
Test Case "stCallCodes":
Test Case "stCallCreateCallCodeTest":
Test Case "stExample":
Test Case "stInitCodeTest":
Test Case "stLogTests":
Test Case "stMemoryTest":
100%
Calling evm2wasm.js (input 10 bytes)...
(Calling evm2wasm.js with command: evm2wasm -e /tmp/hera.evm2wasm.evm.Z0BKYq -o /tmp/hera.evm2wasm.wasm.MUUSpI --charge-per-op)
evm2wasm.js done (output 972 bytes)
Executing...
importGlobals
useGas 0
callDataSize
useGas 3
useGas 3
useGas 0
useGas 9
callDataCopy 8428 0 50
useGas 2
useGas 3
useGas 0
return 8428 60
Test Case "stPreCompiledContracts":
Test Case "stPreCompiledContracts2":
Test Case "stRandom":
Test Case "stRandom2":
Test Case "stRecursiveCreate":
Test Case "stRefundTest":
Test Case "stSolidityTest":
Test Case "stSpecialTest":
Test Case "stSystemOperationsTest":
Test Case "stTransactionTest":
Test Case "stTransitionTest":
Test Case "stWalletTest":
Test Case "stCallDelegateCodesCallCodeHomestead":
Test Case "stCallDelegateCodesHomestead":
Test Case "stHomesteadSpecific":
Test Case "stDelegatecallTestHomestead":
Test Case "stChangedEIP150":
Test Case "stEIP150singleCodeGasPrices":
Test Case "stMemExpandingEIP150Calls":
Test Case "stEIP150Specific":
Test Case "stEIP158Specific":
Test Case "stNonZeroCallsTest":
Test Case "stZeroCallsTest":
Test Case "stZeroCallsRevert":
Test Case "stCodeSizeLimit":
Test Case "stCreateTest":
Test Case "stRevertTest":
Test Case "stStackTests":
Test Case "stStaticCall":
Test Case "stReturnDataTest":
Test Case "stZeroKnowledge":
Test Case "stZeroKnowledge2":
Test Case "stCodeCopyTest":
Test Case "stBugs":
Test Case "stShift":
Test Case "stAttackTest":
Test Case "stMemoryStressTest":
Skipping stQuadraticComplexityTest because --all option is not specified.
Test Case "stBadOpcode":
Test Case "stArgsZeroOneBalance":
Test Case "stEWASMTests":

*** No errors detected
```

**Comment by kyteague** [comment]
Added the `stMemoryTest` to `circle.yml` in 74c8892.

**Comment by axic** [comment]
Thank you @kyteague, this is great!

**Pull request merged**
