### PR TITLE
C++ port

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
Needs makefile. @chfast would you be interested in adding cmake magic to this (loading binaryen and linking with it)?

**Comment by chfast** [comment]
Yes

**Comment by chfast** [comment]
CMake is here: https://github.com/ewasm/evm2wasm/pull/150.

**Comment by chfast** [comment]
Added CMake + Binaryen ExternalProject.

**Comment by axic** [comment]
@chfast can you also add it to travis as a separate task (and perhaps add the line to not build branches)?

(Disregard that the javascript task is failing tests, that is fixed in a different PR)

**Comment by chfast** [comment]
Can I add CircleCI? It performs much better.

**Comment by axic** [comment]
Sure, but can we keep travis for this PR and do circleci separately?

**Comment by Silur** [comment]
guys guys we are working parallel again, https://github.com/Silur/evm2wasm/tree/crewrite
this is what we work on with jake

**Comment by axic** [comment]
@Silur you can rebase that based on this, this is only adding binaryen (also it was created back in december)

**Comment by chfast** [comment]
@axic Axic, does it look right to you? https://travis-ci.org/ewasm/evm2wasm/jobs/327194684
I only intended to upgrade Node JS to 8.

**Comment by axic** [comment]
@chfast cool, it built!

**Pull request merged**
