### PR TITLE
Build and validate documentation too

### PR DESCRIPTION
**Pull request by axic**
Follow up to #206.

### CODE REVIEW

**Comment by axic** [comment]
This is a pain, because the newest `documentation` module uses the commit hash in the output:
```
-[5]: https://github.com/ewasm/evm2wasm/blob/b41de7e99c7ee55f8ebbf4205fa97321288f662f/index.js#L84-L97 "Source code on GitHub"
+[5]: https://github.com/ewasm/evm2wasm/blob/e05d69812f4d860406aeddd7f1db11876a73bf5c/index.js#L84-L97 "Source code on GitHub"
```

**Comment by axic** [comment]
@jakelang it didn't help :(

**Comment by jakelang** [comment]
@axic do we need a package lock file? `npm install` doesn't generate one, maybe we don't need it or we can use a shrinkwrap file instead.
Sorry if this is a dumb recommendation, I don't work with npm

**Comment by axic** [comment]
> do we need a package lock file? npm install doesn't generate one, maybe we don't need it or we can use a shrinkwrap file instead.
> Sorry if this is a dumb recommendation, I don't work with npm

I have not idea at all, don't know why these are needed. Lets try removing it.

**Pull request merged**
